
server:
  port: 8089

#primary
spring:
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60
  primary:
    datasource:
      url: jdbc:mysql://94.191.10.75:3306/test1?characterEncoding=utf-8
      username: root
      password: 159357
      driver-class-name: com.mysql.cj.jdbc.Driver

  #secondary
  secondary:
    datasource:
      url: jdbc:mysql://94.191.10.75:3306/test2?characterEncoding=utf-8
      username: root
      password: 159357
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      primary-dialect: org.hibernate.dialect.MySQL5Dialect
      secondary-dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect