
server:
  port: 8089

# 多数据源配置
#primary
spring:
  primary:
    datasource:
      jdbc-url: jdbc:mysql://94.191.10.75:3306/test1?characterEncoding=utf-8
      username: root
      password: 159357
      driver-class-name: com.mysql.cj.jdbc.Driver

  #secondary
  secondary:
    datasource:
      jdbc-url: jdbc:mysql://94.191.10.75:3306/test2?characterEncoding=utf-8
      username: root
      password: 159357
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:

      ddl-auto: update
      primary-dialect: org.hibernate.dialect.MySQL5Dialect
      secondary-dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect